id: P57EC2ACB
initial_creation_type: input
source_metadata:
  title: 'BA: Proto-BA (Buddhanāmanirdeśa)'
  language: bo
  volumes:
    2f978ddd96ff4337b22c0a51aeb31b97:
      title: 'Chapter I: Nidāna'
      base_file: 'Chapter I: Nidāna.txt'
      work_id: W7293A96D
    3e75d516163d4c438653678fb1589ed6:
      title: 'Chapter II: Praṇidhānacaryā'
      base_file: 'Chapter II: Praṇidhānacaryā.txt'
      work_id: WBBC8A266
    0712e078787e4381ae7d2d0787b482dc:
      title: Title
      base_file: Title.txt
      work_id: W3EFCCD80
  chapter_to_tile: {}
created_at: '2022-03-01T21:20:20.100329'
last_modified_at: '2022-03-01T21:20:20.100351'
